export const SEARCH_RECIPES = 'SEARCH_RECIPES';

export const SERACH_FOODS_INGREDIENTS = 'SEARCH_FOOD_INGREDIENTS';
export const SERACH_DRINKS_INGREDIENTS = 'SEARCH_DRINKS_INGREDIENTS';
export const FOODS_CATEGORIES = 'FOODS_CATEGORIES';
export const DRINKS_CATEGORIES = 'DRINKS_CATEGORIES';
